# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Mukundhan Srinivasan
tagline:          Studying life's engineering
description:      "Another engineer's customary mustings on research, startup, code and life."
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /

author:
  name:           'Mukundhan Srinivasan'
  url:            https://twitter.com/immsrini

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           

gems:
- jekyll-gist
- jekyll-paginate
